---
version: 2

jobs:
  build:
    environment:
      # Configure the JVM and Gradle to avoid OOM errors
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}
      - run:
          name: Install dependencies
          command: ./gradlew build -x test --info
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}
      - persist_to_workspace:
          root: .
          paths:
            - build

  release-production:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Log into docker registry
          command: |
            docker login --username=_ --password=${HEROKU_REGISTRY_TOKEN} registry.heroku.com
      - run:
          name: Build and push image
          command: |
            ./gradlew clean dockerPushHerokuProduction --info
      - run:
          name: Release
          command: |
            export IMAGE_ID=$(docker inspect registry.heroku.com/bojo-prod/web --format={{.Id}})
            curl -X PATCH \
              https://api.heroku.com/apps/bojo-prod/formation \
              -H 'Accept: application/vnd.heroku+json; version=3.docker-releases' \
              -H "Authorization: Bearer ${HEROKU_REGISTRY_TOKEN}" \
              -H 'Content-Type: application/json' \
              -d "{\"updates\":[{\"type\":\"web\",\"docker_image\":\"${IMAGE_ID}\"}]}"
      - run:
          name: Remove docker credentials
          command: |
            rm "${HOME}/.docker/config.json"

  release-staging:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Log into docker registry
          command: |
            docker login --username=_ --password=${HEROKU_REGISTRY_TOKEN} registry.heroku.com
      - run:
          name: Build and push image
          command: |
            ./gradlew clean dockerPushHerokuStaging --info
      - run:
          name: Release
          command: |
            export IMAGE_ID=$(docker inspect registry.heroku.com/bojo-stage/web --format={{.Id}})
            curl -X PATCH \
              https://api.heroku.com/apps/bojo-stage/formation \
              -H 'Accept: application/vnd.heroku+json; version=3.docker-releases' \
              -H "Authorization: Bearer ${HEROKU_REGISTRY_TOKEN}" \
              -H 'Content-Type: application/json' \
              -d "{\"updates\":[{\"type\":\"web\",\"docker_image\":\"${IMAGE_ID}\"}]}"
      - run:
          name: Remove docker credentials
          command: |
            rm "${HOME}/.docker/config.json"

  test-integration:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run integration test
          command: ./gradlew integrationTest

  test-postman:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Run postman test
          command: .circleci/script/execute_postman_test.sh

  test-unit:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run unit test
          command: ./gradlew test

workflows:
  version: 2

  test_and_release_staging:
    jobs:
      - build
      - test-unit:
          requires:
            - build
          filters:
            branches:
              ignore: master
      - test-integration:
          requires:
            - build
          filters:
            branches:
              ignore: master
      - test-postman:
          requires:
            - build
          filters:
            branches:
              ignore: master
      - release-staging:
          requires:
            - test-integration
            - test-postman
            - test-unit
          filters:
            branches:
              ignore: master

  test_and_release_production:
    jobs:
      - build
      - test-unit:
          requires:
            - build
          filters:
            branches:
              only: master
      - test-integration:
          requires:
            - build
          filters:
            branches:
              only: master
      - test-postman:
          requires:
            - build
          filters:
            branches:
              only: master
      - release-staging:
          requires:
            - test-integration
            - test-postman
            - test-unit
          filters:
            branches:
              only: master
      - hold:
          type: approval
          requires:
            - release-staging
      - release-production:
          requires:
            - hold
          filters:
            branches:
              only: master